### ISSUE TITLE
Truncated values?

### ISSUE THREAD

**Issue by guithib** [nuket/google-sheets-geocoding-macro#1]
Hi,

I am very impressed by your script, I easily managed to geocode several addresses.
But, it seems long values could be truncated. So markers are not very accurate on Google Maps :/

---

For example:
**Liverpool**:
Returned values by your script : 
Latitude: 53,4083714
Longitude: -2,9915726

Returned values by [gps-coordinates.net](http://www.gps-coordinates.net/)
Latitude: 53.4083714
Longitude: -2.9915726000000404

---

Do you know why long values are be shorten? 
I do not see specific settings in Google Sheet for that.

Thanks for your support!

**Comment by nuket** [comment]
Afraid there's not much I can do about that. The 7-decimal precision is what Google's Geocoding API returns, and I have no control over what they return. 7-decimals is pretty accurate though. Using a [great circle calculator](http://www.gpsvisualizer.com/calculators), a difference of .0000001 degrees in any cardinal direction is less than a meter of distance at the latitude, longitude provided.
