### ISSUE TITLE
Map Cells in Mapping image throws error

### ISSUE THREAD

**Issue by TacticalPants** [nuket/google-sheets-geocoding-macro#14]
Hi,

I'm attempting to run the 'Map cells in mapping sheet' function from the menu and I am flagged with this error 'TypeError: Cannot read property 'getRange' of null'.  I initiate the function by highlighting three cells, the first two of which are the Lat and Long coordinates, then clicking the function in the menu.  How can I resolve this error?

**Comment by nuket** [comment]
If you do this in the Mapping tab, it should work. It does not work in the 
Test Addresses or Reverse To Components tabs.

**Comment by nuket** [comment]
Explainer: https://github.com/nuket/google-sheets-geocoding-macro#map-cells
