### ISSUE TITLE
Error Callback

### ISSUE THREAD

**Issue by brunomaion** [nuket/google-sheets-geocoding-macro#15]
when I manipulate a spreadsheet of 1000 rows it gives an error, callback limit of script, why? I need for scientific research

**Comment by nuket** [comment]
Try selecting up to 500 rows at a time and see if that helps. It could be a 
limitation of the Google API.

**Comment by brunomaion** [comment]
Why quota limit in App Script (Google Cloud) is 1000 per minute and for Script is 1000 for day? Is there any way to get add limit free?

**Comment by nuket** [comment]
This is a question for Google.
