### ISSUE TITLE
Can't understand how to use reverse geocoding 

### ISSUE THREAD

**Issue by matthieuhelary** [nuket/google-sheets-geocoding-macro#2]
Can you help ?

**Comment by mericawebproject** [comment]
Assuming you followed the instructions to copy that text and put it in the script section then hit save... and you now see the geocode drop down box..
From there you need to have a column labeled lat, long, and address. Have your lat and long in the respective columns  and then highlight all three columns, then click the geocode drop down box then click geocode. It will start working then.

**Comment by solarworldusa** [comment]
Is there any way to at least increase the the number of calls this script can make in a day? "Service invoked too many times for one day: geocode"

**Comment by mericawebproject** [comment]
I ran into the same problem

**Comment by solarworldusa** [comment]
This script works for about 1000 per day, but you have to do it in increments. Use =geoGetLatLon( to call it in the lat cell.
`function geoGetLatLon(address) {
if (address == '') {
throw Error("No address provided");
}
var geocoder = Maps.newGeocoder();
var location;
  Utilities.sleep(1000);
location = geocoder.geocode(address);
if (location.status == 'OK') {
lat = location["results"][0]["geometry"]["location"]["lat"];
lng = location["results"][0]["geometry"]["location"]["lng"];
return [[lat,lng]];
} else {
throw Error("Geocode failed");
}
};`

**Comment by nuket** [comment]
Yeah, the limit on the number of geocode operations per day is set by 
Google. I'm guessing that if you have a certain type of Google API key 
(paid), it would be possible to do more.

**Comment by nuket** [comment]
Closing, added a picture to README of how this is to be used.

**Comment by thomaslarkin** [comment]
can you provide instructions on how to add the google api key to the code?
