### ISSUE TITLE
Multi-column addresses

### ISSUE THREAD

**Issue by ChasingLeaves** [nuket/google-sheets-geocoding-macro#5]
I use sheets which have multiple columns for addresses (e.g. address 1, address 2, town, postal code), but the script doesn't appear to support this (it won't geocode for two selected columns - only one). I know that I could concatenate the addresses, but is there a way to amend the script so that it can support multi-column addresses?

**Comment by nuket** [comment]
Try it now, I've added support for multicolumn address data.
